### PR TITLE
Add escaped characters to the AST

### LINKED ISSUE #21: Issues with substring processing in parameter expansion
Consider the following snippet:
```
FOO="\\a"
echo ${FOO#*\\}
```
What I expect this to output is `a` (and this is what `dash` and `bash` does), but `smoosh` outputs `\a`.

Another issue:
```
FOO="a?b"
echo ${FOO#*"?"}
```
This should output `b` (as it does on `dash` and `bash`), but with `smoosh` is outputs `?b`, because it does not consider the question mark as escaped.

It seems that when `try_match_substring` receives the pattern, it is already fully expanded, with quotes removed, despite the code assuming that it still has quotes and escaping backslashes in it.

A similar pattern to the first example is used in the Modernish test suite to iterate over a string, this bug causes it to be stuck in an endless loop forever.

### PR DESCRIPTION
**Pull request by tucak**
This fixes #21.

### CODE REVIEW

**Comment by tucak** [comment]
Seems like the failures are CI issues and not my fault.

**Comment by mgree** [comment]
Just fixed CI... could you fast-forward, please?

**Comment by tucak** [comment]
Looks like this time they all pass!

**Comment by mgree** [comment]
Perfect! Thank you so much for this PR; @Ishaangandhi is currently hooking Smoosh up to Morbig, and this will make his life much easier. 😄

**Pull request merged**
